../../miniRT green_sp_blue_ambien_01.rt &
../../miniRT green_sp_blue_ambien_02.rt &
../../miniRT green_sp_blue_ambien_03.rt &
../../miniRT green_sp_blue_ambien_04.rt &
../../miniRT green_sp_blue_ambien_05.rt &
../../miniRT green_sp_blue_ambien_06.rt &
../../miniRT green_sp_blue_ambien_07.rt &
../../miniRT green_sp_blue_ambien_08.rt &
../../miniRT green_sp_blue_ambien_09.rt &
../../miniRT red_pl_blue_ambient_01.rt &
../../miniRT red_pl_blue_ambient_02.rt &
../../miniRT red_pl_blue_ambient_03.rt &
../../miniRT red_pl_blue_ambient_04.rt &
../../miniRT red_pl_blue_ambient_05.rt &
../../miniRT red_pl_blue_ambient_06.rt &
../../miniRT red_pl_blue_ambient_07.rt &
../../miniRT red_pl_blue_ambient_08.rt &
../../miniRT red_pl_blue_ambient_09.rt &
../../miniRT green_sp_red_ambien_01.rt &
../../miniRT green_sp_red_ambien_02.rt &
../../miniRT green_sp_red_ambien_03.rt &
../../miniRT green_sp_red_ambien_04.rt &
../../miniRT green_sp_red_ambien_05.rt &
../../miniRT green_sp_red_ambien_06.rt &
../../miniRT green_sp_red_ambien_07.rt &
../../miniRT green_sp_red_ambien_08.rt &
../../miniRT green_sp_red_ambien_09.rt &
